name: Scheduled Workflow

on:
  schedule:
    - cron: '15 9,10,11,12,13,14,15 * * 1-5'  # Run at 15 minutes past each hour from 9 AM to 3 PM on weekdays
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-scheduled-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.7'  # Specify the exact Python version

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            .venv
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements_dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements_dev.txt

      - name: Set environment variables
        run: echo "Environment variables set"
        env:
          API_KEY: ${{ secrets.API_KEY }}
          USERNAME: ${{ secrets.USERNAME }}
          PWD: ${{ secrets.MPIN }}
          TOKEN: ${{ secrets.TOKEN }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
    
      - name: Run script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          USERNAME: ${{ secrets.USERNAME }}
          PWD: ${{ secrets.MPIN }}
          TOKEN: ${{ secrets.TOKEN }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: |
          source .venv/bin/activate
          python btlivetradingmain.py
