name: Scheduled Workflow

on:
  schedule:
    - cron: '45 3-9 * * 1-5'  # 9:15 AM to 3:15 PM IST on weekdays
  workflow_dispatch:

jobs:
  run-scheduled-task:
    runs-on: ubuntu-22.04

    concurrency:
      group: master-push
      cancel-in-progress: true

    env:
      API_KEY: ${{ secrets.API_KEY }}
      USERNAME: ${{ secrets.USERNAME }}
      MPIN: ${{ secrets.MPIN }}
      TOKEN: ${{ secrets.TOKEN }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.7'

      - name: Remove existing virtual environment
        run: rm -rf .venv

      - name: Cache pip only (no .venv)
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements_dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade --force-reinstall pip setuptools wheel
          pip install -r requirements_dev.txt

      - name: Clean logs folder before script run
        run: rm -rf logs/*

      - name: Run script
        run: |
          source .venv/bin/activate
          python btlivetradingmain.py

      - name: Debug git status before commit
        run: |
          git remote -v
          git fetch origin
          git status
          git log -5 --oneline --graph
          git log origin/master -5 --oneline --graph

      - name: Commit and push changes
        run: |
          set -e

          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

          git fetch origin
          git checkout master
          git pull --rebase origin master

          git add .

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m 'Automated update from scheduled workflow'
            git push origin master
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
